// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikfvgpgqykprmflramem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZnZncGdxeWtwcm1mbHJhbWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDU0MDcsImV4cCI6MjA3NjgyMTQwN30.9Of_O42GH3TJ6Jkb5GGt2puDo0B5wST0LBslj6z6uvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});